/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class BillRunTest {
    @Test public void testSomeLibraryMethod() {
        BillCalculator billCalculator = new BillCalculator();
        assertTrue("someLibraryMethod should return 'true'", billCalculator.someLibraryMethod());
    }
}
